spring:
  application:
    name: examen-practico
  datasource:
    url: jdbc:postgresql://localhost:5432/bside
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate


server:
  port: 8090
  servlet:
    context-path: /base


